// Maps a driver/constructor "nationality" demonym (as returned by the Ergast/Jolpi API,
// e.g. "British", "Dutch", "Monegasque") to a flag emoji.
const NATIONALITY_FLAGS = {
    American: '🇺🇸',
    Argentine: '🇦🇷',
    Australian: '🇦🇺',
    Austrian: '🇦🇹',
    Belgian: '🇧🇪',
    Brazilian: '🇧🇷',
    British: '🇬🇧',
    Canadian: '🇨🇦',
    Chilean: '🇨🇱',
    Chinese: '🇨🇳',
    Colombian: '🇨🇴',
    Czech: '🇨🇿',
    Danish: '🇩🇰',
    Dutch: '🇳🇱',
    Emirati: '🇦🇪',
    Estonian: '🇪🇪',
    Finnish: '🇫🇮',
    French: '🇫🇷',
    German: '🇩🇪',
    Hungarian: '🇭🇺',
    Indian: '🇮🇳',
    Indonesian: '🇮🇩',
    Irish: '🇮🇪',
    Italian: '🇮🇹',
    Japanese: '🇯🇵',
    Malaysian: '🇲🇾',
    Mexican: '🇲🇽',
    Monegasque: '🇲🇨',
    'New Zealander': '🇳🇿',
    Polish: '🇵🇱',
    Portuguese: '🇵🇹',
    Russian: '🇷🇺',
    Saudi: '🇸🇦',
    'South African': '🇿🇦',
    Spanish: '🇪🇸',
    Swedish: '🇸🇪',
    Swiss: '🇨🇭',
    Thai: '🇹🇭',
    Venezuelan: '🇻🇪',
};

export const getNationalityFlag = (nationality) => NATIONALITY_FLAGS[nationality] || '🏁';
